micronaut:
  application:
    name: cicd-demo
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
datasources:
  default:
    url: ${DATASOURCES_DEFAULT_URL}
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: ${DATASOURCES_DEFAULT_USERNAME}
    password: ${DATASOURCES_DEFAULT_PASSWORD}
    schema-generate: NONE
    dialect: ORACLE