datasources:
  default:
    url: ${DATASOURCE_URL}
    connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    schema-generate: NONE
    dialect: ORACLE