name: cicd-demo
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: self-hosted
    steps:

      - name: 'Start build job'
        run: |
          echo "Starting the build job. Work dir is $GITHUB_WORKSPACE"

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set Work Dir'
        run: echo ::set-env name=WORK_DIR::$GITHUB_WORKSPACE

      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Check Java Version'
        run: |
          java --version

      - name: 'Run Tests'
        run: |
          #./gradlew test
          echo "Run tests..."

      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: build/reports/tests/test/*

      - name: 'Assemble JAR'
        run: |
          ./gradlew assemble

      - name: 'Get Version Number'
        run: |
          echo "::set-env name=VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"

      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'cicd-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar

      - name: 'Write Config & Key Files'
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config-tmp
          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config-tmp
          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config-tmp
          echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config-tmp
          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config-tmp
          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config-tmp
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config-tmp
          sudo sh -c 'mv ~/.oci/config-tmp ~/.oci/config'
          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
          echo "${{secrets.VM_SSH_PUB_KEY}}" >> ~/.oci/id_vm.pub
          sudo mkdir ${{env.WORK_DIR}}/wallet
          sudo sh -c  'echo "${{secrets.WALLET_CWALLET}}" | base64 -d >> ${{env.WORK_DIR}}/wallet/cwallet.sso'
          sudo sh -c  'echo "${{secrets.WALLET_EWALLET}}" | base64 -d >> ${{env.WORK_DIR}}/wallet/ewallet.p12'
          sudo sh -c  'echo "${{secrets.WALLET_KEYSTORE}}" | base64 -d >> ${{env.WORK_DIR}}/wallet/keystore.jks'
          sudo sh -c  'echo "${{secrets.WALLET_OJDBC}}" | base64 -d >> ${{env.WORK_DIR}}/wallet/ojdbc.properties'
          sudo sh -c  'echo "${{secrets.WALLET_SQLNET}}" | base64 -d >> ${{env.WORK_DIR}}/wallet/sqlnet.ora'
          sudo sh -c  'echo "${{secrets.WALLET_TNSNAMES}}" | base64 -d >> ${{env.WORK_DIR}}/wallet/tnsnames.ora'
          sudo sh -c  'echo "${{secrets.WALLET_TRUSTSTORE}}" | base64 -d >> ${{env.WORK_DIR}}/wallet/truststore.jks'
          sudo sh -c  'chown opc ${{env.WORK_DIR}}/wallet/'
          sudo sh -c  'chgrp opc ${{env.WORK_DIR}}/wallet/'

      - name: 'Login To OCIR'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.OCIR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.OCIR_PASSWORD }}
          DOCKER_REGISTRY_URL: phx.ocir.io

      - name: 'Docker Build'
        run: docker build -t phx.ocir.io/toddrsharp/cicd-demo/cicd-demo:latest .

      - name: 'Docker Push'
        uses: actions-hub/docker@master
        with:
          args: push phx.ocir.io/toddrsharp/cicd-demo/cicd-demo:latest

      - name: 'Create Password Secret'
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.OKE_KUBE_CONFIG }}
        with:
          args: "create secret generic cicd-demo-secrets --from-literal=dbPassword='${{secrets.OKE_DB_PASSWORD}}' --save-config --dry-run -o yaml | kubectl apply -f -"

      - name: 'Deploy To Kubernetes'
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.OKE_KUBE_CONFIG }}
        with:
          args: '"apply -f ./k8s/app.yaml"'

      - name: 'Kill Pod'
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.OKE_KUBE_CONFIG }}
        with:
          args: '"delete pod $(kubectl get pod -l app=cicd-demo -o jsonpath="{.items[0].metadata.name}")"'